# Generated by Django 3.1.7 on 2021-03-14 11:09

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20210312_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='acquired',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='owner',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
